spring.application.name=invoice-fraud-detection


spring.datasource.url=${DB_Url}
spring.datasource.username=${DB_Username}
spring.datasource.password=${DB_Password}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jackson.serialization.fail-on-empty-beans=false

logging.level.org.hibernate.SQL=DEBUG

server.port=8080
